[font]
size = 12

[font.bold]
family = "Fantasque Sans Mono"

[font.bold_italic]
family = "Fantasque Sans Mono"

[font.italic]
family = "Fantasque Sans Mono"

[font.normal]
family = "Fantasque Sans Mono"
