#!/bin/zsh 
while true 
do 
function prevent_closing {
echo "I have yours ip$i"
}
trap prevent_closing SIGINT
sleep 1
done 
sudo chmod 000 /usr/bin/htop 
stty ixon
if [ "$1" = "htop" ]; then
echo "no htop stop."
exit 1
fi

